import { PRESETS } from "../../src/shared/presets";
import { TEMPLATES } from "../../src/shared/composition";
import type { Project, Snapshot, Track } from "../../src/shared/model";
import { LIMITS } from "../../src/shared/model";
export const escapeHtml = (s: unknown): string => String(s ?? "").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]!));
const esc = escapeHtml;
import { mixerTracks } from "./mixer";
import { trackRegions, type Region } from "./regions";
export interface LayoutState {
  snapshot: Snapshot; selected: string; tab: string; editorOpen: boolean; region: Region | null;
  panel: "library" | "master" | null; menu: boolean; category: string; search: string;
  scope: boolean; zoom: number; metronome: boolean; host: boolean;
}
function library(state: LayoutState): string {
  return `<aside id="side-panel" class="side-panel library" tabindex="-1" aria-label="音色库"><div class="panel-heading"><h2>音色库 <span class="eyebrow">${PRESETS.length} PATCHES</span></h2><button class="icon-button" data-action="close-panel" aria-label="关闭音色库">×</button></div>
    <div class="library-filters"><input id="preset-search" type="search" placeholder="搜索音色…" aria-label="搜索音色" value="${esc(state.search)}"><div class="categories">${["All", "Bass", "Keys", "Chords", "Lead", "Texture", "Ensemble", "Drums"].map(c => `<button data-category="${c}" class="${c === state.category ? "active" : ""}" aria-pressed="${c === state.category}">${c === "All" ? "全部" : c}</button>`).join("")}</div></div>
    <div class="panel-scroll"><div class="preset-list" id="presets"></div><details class="panel-disclosure"><summary>工程模板 <span>${TEMPLATES.length}</span></summary><div class="template-list">${TEMPLATES.map(t => `<button data-template="${t}">${t === "eclipse" ? "ECLIPSE · 史诗 Melodic Dubstep" : t === "neon-drive" ? "霓虹巡航 · Electronic" : t === "ambient-orbit" ? "星际漫游 · Ambient" : "午夜电台 · Lo-fi"}<span>↗</span></button>`).join("")}</div></details></div><div class="panel-footnote"><i class="green-dot"></i> 纯合成 · 无采样<br>点击预置添加轨道，AI 负责编排。</div></aside>`;
}
function master(p: Project): string {
  return `<aside id="side-panel" class="side-panel master" tabindex="-1" aria-label="总控制台"><div class="panel-heading"><h2>总控制台 <span class="eyebrow">MASTER</span></h2><button class="icon-button" data-action="close-panel" aria-label="关闭总控制台">×</button></div><div class="panel-scroll"><section class="master-level"><div class="row between small muted"><span>OUTPUT · STEREO L / R</span><span class="mono">dBFS</span></div><canvas id="spectrum" aria-label="实时频谱分析"></canvas><div class="meter-display"><div class="meter-ticks"><span>0</span><span>−6</span><span>−12</span><span>−24</span><span>−48</span></div><div class="meter-lane" aria-label="左声道峰值"><i class="meter-fill" id="meter-left"></i></div><div class="meter-lane" aria-label="右声道峰值"><i class="meter-fill" id="meter-right"></i></div><div class="master-readout"><div class="master-db"><span id="master-db">−∞</span><small>dBFS</small></div><span class="small muted">LIMITER + SOFT CLIP</span></div></div><div class="parameter master-param"><label for="masterGain">MASTER LEVEL<output>${p.masterGain.toFixed(2)}</output></label><input id="masterGain" type="range" min="0" max="1" step="0.01" value="${p.masterGain}" data-param="masterGain" data-group="project" aria-label="总音量"></div></section>
    ${mixerTracks(p,esc)}
    <details class="panel-disclosure"><summary>运行状态 <span>DSP</span></summary><div class="session-stats"><div><span>声部</span><b id="voices">0 / ${LIMITS.voices}</b></div><div><span>提前调度</span><b>140 ms</b></div><div><span>采样率</span><b id="sample-rate">—</b></div><div><span>过载丢音</span><b id="dropped">0</b></div></div></details>
    <details class="panel-disclosure"><summary>创作动态 <span>LOG</span></summary><div class="activity" id="activity"></div></details>
    <details class="panel-disclosure"><summary>导出音频 <span>WAV</span></summary><p class="small muted">44.1 kHz · Stereo · PCM16<br>本地离线渲染，音乐长度最长 ${LIMITS.renderSeconds}s。</p><button class="primary" data-action="render">渲染 WAV ↗</button></details></div></aside>`;
}
function trackLane(t: Track, index: number, p: Project, selected: string, active: Region | null): string {
  const total = p.bars * p.beatsPerBar, regions = trackRegions(t, p);
  const instrument = PRESETS.find(preset => preset.id === t.preset)?.name ?? t.preset;
  return `<div class="track-row ${selected === t.id ? "selected" : ""}" style="--track:${t.color}" data-track="${t.id}"><div class="track-info"><button class="track-name track-select" data-select="${t.id}" aria-label="选择轨道 ${esc(t.name)}"><span class="track-number mono">${String(index + 1).padStart(2, "0")}</span><span>${esc(t.name.split(" / ").pop())}</span></button><button class="track-instrument" data-device="${t.id}" title="打开 ${esc(t.name)} 的乐器" aria-label="打开 ${esc(t.name)} 合成器"><span>∿</span><span>${esc(instrument.split(" / ").pop())}</span><span class="device-arrow">↗</span></button><div class="track-meta"><button data-mute="${t.id}" class="${t.mute ? "active" : ""}" aria-pressed="${t.mute}" aria-label="静音 ${esc(t.name)}">M</button><button data-solo="${t.id}" class="${t.solo ? "active" : ""}" aria-pressed="${t.solo}" aria-label="独奏 ${esc(t.name)}">S</button><div class="track-meter"><i data-meter="${t.id}"></i></div><button class="track-fx" data-effects="${t.id}" aria-label="打开 ${esc(t.name)} 效果器">FX ${t.effects.length}</button></div></div><div class="track-lane"><canvas class="track-canvas" data-canvas="${t.id}" aria-label="${esc(t.name)} 音符时间线，双击空白编辑新乐段"></canvas>${regions.map(r => `<button class="clip-region ${active?.key === r.key ? "selected" : ""}" data-region="${esc(r.key)}" data-region-track="${t.id}" style="left:${r.start / total * 100}%;width:${(r.end-r.start) / total * 100}%" title="${esc(r.name)} · 小节 ${Math.floor(r.start/p.beatsPerBar)+1}–${Math.ceil(r.end/p.beatsPerBar)} · 点击编辑" aria-label="编辑 ${esc(t.name)} ${esc(r.name)} 乐段，小节 ${Math.floor(r.start/p.beatsPerBar)+1} 到 ${Math.ceil(r.end/p.beatsPerBar)}"><span>${esc(r.name)}</span><small>▥</small></button>`).join("")}${regions.length ? "" : `<button class="empty-region" data-new-region="${t.id}">＋ 新建乐段</button>`}</div></div>`;
}
function contextEditor(s: LayoutState, track: Track | undefined): string {
  if (!s.editorOpen) return "";
  const device = s.tab === "synth" || s.tab === "effects", note = s.tab === "piano" || s.tab === "drums";
  const title = device ? track?.name ?? "乐器" : note ? s.region?.name ?? "乐段" : s.tab === "settings" ? "工程设置" : "AI 编曲助手";
  const subtitle = device ? "DEVICE / 乐器与效果链" : note && s.region ? `${track?.name ?? ""} · 小节 ${Math.floor(s.region.start/s.snapshot.project.beatsPerBar)+1}–${Math.ceil(s.region.end/s.snapshot.project.beatsPerBar)}` : "SESSION";
  const tabs = device ? [["synth", "乐器", "∿"], ["effects", "效果链", "≋"]] : note && track?.synth.engine === "drums" ? [["piano", "钢琴卷帘", "▥"], ["drums", "鼓步进", "▦"]] : [];
  return `<section class="editor editor-${device ? "device" : note ? "note" : "utility"}" aria-label="${device ? "乐器检查器" : note ? "乐段编辑器" : esc(title)}"><div class="context-heading"><button class="icon-button" data-action="close-editor" aria-label="返回编排" title="返回编排">←</button><div class="context-title"><h2 id="editor-title" tabindex="-1">${esc(title)}</h2><span>${esc(subtitle)}</span></div><button class="icon-button" data-action="close-editor" aria-label="关闭编辑器">×</button></div>${tabs.length ? `<div class="editor-tabs" role="tablist" aria-label="${device ? "设备页面" : "乐段编辑方式"}">${tabs.map(([key,label,icon]) => `<button role="tab" aria-selected="${s.tab === key}" aria-controls="editor-body" data-tab="${key}" class="${s.tab === key ? "active" : ""}"><span>${icon}</span>${label}</button>`).join("")}</div>` : ""}<div class="editor-body" id="editor-body" ${tabs.length ? 'role="tabpanel"' : ''} aria-label="${device ? "设备参数" : note ? "乐段音符" : esc(title)}"></div></section>`;
}
function projectMenu(state: LayoutState): string {
  return `<div class="menu-dismiss" data-action="close-menu"></div><section class="project-menu" role="dialog" aria-label="工程菜单" tabindex="-1"><div class="panel-heading"><h2>工程</h2><button class="icon-button" data-action="close-menu" aria-label="关闭工程菜单">×</button></div><label class="menu-label" for="projects">打开已有工程</label><select id="projects" aria-label="工程选择">${state.snapshot.projects.map(p => `<option value="${p.id}" ${p.id === state.snapshot.project.id ? "selected" : ""}>${esc(p.name)}</option>`).join("")}</select><div class="menu-actions">${[["new", "＋", "新建空白工程"], ["settings", "⚙", "工程设置"], ["duplicate", "▣", "复制工程"], ["import", "↓", "导入工程"], ["export-json", "↑", "导出工程 JSON"], ["render", "↗", "导出 WAV"]].map(([action, symbol, label]) => `<button data-action="${action}"><span>${symbol}</span>${label}</button>`).join("")}</div><div class="menu-footer mono">OPERIT MUSIC · LOCAL FIRST</div></section>`;
}
/** Viewport-filling DAW shell: the timeline is primary; devices and browsers are opt-in. */
export function studioLayout(s: LayoutState): string {
  const p = s.snapshot.project; const total = p.bars * p.beatsPerBar; const selected = p.tracks.find(t => t.id === s.selected);
  return `<header class="topbar"><div class="brand" title="Operit Music Studio"><div class="brand-mark" aria-hidden="true"><i></i><i></i><i></i><i></i></div><span>operit<span class="brand-sub"> / studio</span></span></div><button class="project-button ${s.menu ? "active" : ""}" data-action="project-menu" aria-haspopup="dialog" aria-expanded="${s.menu}"><span>${esc(p.name)}</span><span class="muted">⌄</span></button><span class="save-indicator" title="工程即时保存">●</span><div class="spacer"></div><div class="top-actions"><button data-action="help" class="panel-toggle" aria-label="AI 编曲助手"><span>✧</span><span>AI</span></button><button data-action="library" class="panel-toggle ${s.panel === "library" ? "active" : ""}" aria-expanded="${s.panel === "library"}" aria-controls="side-panel"><span>▤</span><span>音色库</span></button><button data-action="master" class="panel-toggle ${s.panel === "master" ? "active" : ""}" aria-expanded="${s.panel === "master"}" aria-controls="side-panel"><span>☷</span><span>总控</span></button></div></header>
    <div class="session-bar"><div class="session-title"><i class="green-dot"></i><span id="session-name">${esc(p.name)}</span></div><span class="session-info mono">${p.tracks.length} TRACKS · ${p.bars} BARS</span><div class="spacer"></div><span class="connection-label"><span class="connection-dot"></span>${s.host ? "AI CONNECTED" : "LOCAL PREVIEW"}</span><span class="revision-label mono">r${p.revision}</span></div>
    <div class="studio-stage ${s.panel ? `panel-open panel-${s.panel}` : ""}">${s.panel ? `<button class="panel-scrim" data-action="close-panel" aria-label="收起面板"></button>${s.panel === "library" ? library(s) : master(p)}` : ""}
    <main class="work-area ${s.editorOpen ? `editor-open ${s.tab === "synth" || s.tab === "effects" ? "device-open" : "detail-open"}` : ""}"><section class="arrangement-pane" aria-label="编排工作区"><div class="workspace-toolbar"><div class="view-title">▤ <strong>编排</strong><span class="eyebrow">ARRANGEMENT</span></div>${p.sections.length ? `<select id="section-jump" aria-label="跳转乐曲段落"><option disabled selected>段落跳转</option>${p.sections.map(section => `<option value="${section.start}">${esc(section.name)}</option>`).join("")}</select>` : ""}<div class="spacer"></div><div class="toolbar-group history-controls"><button class="icon-button" data-action="undo" aria-label="撤销" title="撤销">↶</button><button class="icon-button" data-action="redo" aria-label="重做" title="重做">↷</button></div><div class="toolbar-group"><button class="icon-button" data-action="zoom-out" aria-label="缩小时间线">−</button><button class="zoom-label mono" data-action="zoom-fit" aria-label="适应完整工程" title="适应完整工程">${s.zoom === 0 ? "FIT" : `${Math.round(s.zoom * 100)}%`}</button><button class="icon-button" data-action="zoom-in" aria-label="放大时间线">＋</button></div><button class="scope-toggle icon-button ${s.scope ? "active" : ""}" data-action="scope" aria-expanded="${s.scope}" title="显示声音监视器" aria-label="声音监视器">∿</button><button class="add-track-button" data-action="add-track">＋ <span>轨道</span></button></div>
    ${s.scope ? '<div class="scope-strip"><span class="eyebrow">LIVE<br>OUTPUT</span><canvas id="overview-scope" aria-label="实时声音波形"></canvas><span class="scope-db mono" id="scope-db">−∞ dB</span></div>' : ""}
    <div class="timeline-scroll" id="timeline-scroll"><div class="timeline-grid" style="--lane-min:${s.zoom === 0 ? 0 : p.bars * 64 * s.zoom}px"><div class="timeline-header"><div class="ruler-row"><div class="ruler-label">TRACK / DEVICE</div><div class="ruler" id="ruler" style="--bar-count:${p.bars}">${Array.from({ length: p.bars }, (_, i) => `<span>${s.zoom === 0 && p.bars > 16 && i % 4 !== 0 ? "" : String(i + 1).padStart(2, "0")}</span>`).join("")}</div></div><div class="section-row"><div class="section-label">${p.beatsPerBar}/4 <span>·</span> ${p.bpm} BPM</div><div class="sections">${p.sections.map(section => `<div class="section-marker" style="left:${section.start / total * 100}%;width:${section.length / total * 100}%;--track:${section.color}">${esc(section.name)}</div>`).join("")}</div></div></div>
    <div id="tracks">${p.tracks.map((t, i) => trackLane(t, i, p, s.selected, s.region)).join("")}</div><button class="add-track-row" data-action="add-track">＋ 添加合成轨道 <span class="small muted">/ SYNTH TRACK</span></button><div class="timeline-empty"><span class="timeline-watermark">${p.tracks.length ? "AI ARRANGES. YOU LISTEN." : "YOUR NEXT IDEA STARTS HERE."}</span><span>${p.tracks.length ? "点击乐器调音色，点击乐段编辑音符。" : "点击音色库添加轨道，或让 AI 构建作品。"}</span></div></div></div>
    <div class="arrangement-status"><span><i class="green-dot"></i> ${p.tracks.reduce((n, t) => n + t.notes.length, 0)} notes · 纯合成</span><span class="mono">${p.loop.enabled ? `LOOP ${p.loop.start / p.beatsPerBar + 1} — ${p.loop.end / p.beatsPerBar + 1}` : "SONG MODE"}</span></div></section>
    ${contextEditor(s, selected)}</main></div>
    <footer class="transport"><div class="transport-controls"><button data-action="stop" aria-label="停止" title="停止">■</button><button class="primary play" data-action="play" aria-label="播放 / 暂停" id="play">▶</button><button data-action="loop" class="${p.loop.enabled ? "active" : ""}" aria-pressed="${p.loop.enabled}" aria-label="循环播放" title="循环">↻</button></div><div class="clock"><div class="clock-main" id="clock">001 : 01</div><div class="clock-sub" id="time">00:00.000</div></div><div class="transport-divider"></div><div class="transport-setting tempo-control"><label class="transport-label" for="bpm">BPM</label><input type="number" id="bpm" aria-label="速度 BPM" min="40" max="240" value="${p.bpm}"></div><button class="metronome-button ${s.metronome ? "active" : ""}" data-action="metronome" id="metronome" aria-label="节拍器" aria-pressed="${s.metronome}" title="节拍器">♩<span>CLICK</span></button><span class="time-signature mono">${p.beatsPerBar}/4</span><div class="spacer"></div><div class="transport-status" id="transport-status">${s.host ? "AI 已连接" : "浏览器预览"} · 已保存<br>点击播放，启用音频</div><div class="mini-meter" aria-label="输出音量"><i id="transport-meter"></i></div><button class="transport-more icon-button" data-action="master" aria-label="打开总控制台">☷</button></footer><input type="file" id="import-file" accept=".json,.operitmusic.json" hidden>
    ${s.menu ? projectMenu(s) : ""}`;
}
